import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 * Class extending KeyAdapter class and implementing methods to control snake with keyboard input generated by player
 */
public class KeyInput extends KeyAdapter {

    private Snake snake;
    private boolean[] keyDown = new boolean[4];

    /**
     * Constructor of KeyInput
     * @param snake Snake object which will be controlled by player
     */
    public KeyInput(Snake snake){
        this.snake = snake;
        keyDown[0] = false;
        keyDown[1] = false;
        keyDown[2] = false;
        keyDown[3] = false;
    }

    /**
     * Method invoked when key is pressed.
     * Implements ability to control snake with arrow keys.
     * Sets desired velocity of snake according to which arrow key is pressed.
     * @param e KeyEvent object generated when key is pressed
     */
    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();

        if(key == KeyEvent.VK_UP){
            snake.setVelY(-5);
            keyDown[0] = true;
        }
        if(key == KeyEvent.VK_DOWN){
            snake.setVelY(5);
            keyDown[1] = true;
        }
        if(key == KeyEvent.VK_RIGHT){
            snake.setVelX(5);
            keyDown[2] = true;
        }
        if(key == KeyEvent.VK_LEFT){
            snake.setVelX(-5);
            keyDown[3] = true;
        }



    }

    /**
     * Method invoked when key is released.
     * Sets velocity to zero when keys are released.
     * @param e KeyEvent object generated when key is pressed
     */
    public void keyReleased(KeyEvent e) {
        int key = e.getKeyCode();

        if(key == KeyEvent.VK_UP){
            keyDown[0] = false;
        }
        if(key == KeyEvent.VK_DOWN){
            keyDown[1] = false;
        }
        if(key == KeyEvent.VK_RIGHT){
            keyDown[2] = false;
        }
        if(key == KeyEvent.VK_LEFT){
            keyDown[3] = false;
        }

        if(!keyDown[0] && !keyDown[1]) snake.setVelY(0);
        if(!keyDown[2] && !keyDown[3]) snake.setVelX(0);
    }
}
